ml_user_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MlUserBundle:Default:index }

ml_user_accueil:
    pattern: /user/
    defaults: { _controller: MlUserBundle:User:index }

ml_user_see:
    pattern: /user/see
    defaults: { _controller: MlUserBundle:User:see }

ml_user_add:
    pattern: /user/add
    defaults: { _controller: MlUserBundle:User:add }

ml_user_delete:
    pattern: /user/delete
    defaults: { _controller: MlUserBundle:User:delete }
